FROM public.ecr.aws/lambda/provided:al2

RUN yum install -y gcc llvm clang zip

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
ENV PATH $PATH:/root/.cargo/bin
RUN rustup install stable

VOLUME /code
WORKDIR /code

ADD build.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/build.sh
ENTRYPOINT ["/usr/local/bin/build.sh"]
